org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# android.newDsl flag removed - conflicts with AGP 9+

org.gradle.java.home=C:/Program Files/Java/jdk-22
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

# Fix: Kotlin incremental compiler crashes on Windows khi project (D:) và pub cache (C:) khác ổ đĩa
kotlin.incremental=false
